
//action type

export const actionTypes = {
    LOGIN : 'LOGIN',
    LOGOUT : 'LOGOUT',
    REGISTER_SUCESS : 'REGISTER_SUCESS',
    REGISTER_ERROR : 'REGISTER_ERROR',
    GET_MOVIES_SUCCESS:'GET_MOVIES_SUCCESS',
    GET_MOVIES_ERROR:'GET_MOVIES_ERROR',
    GET_MOVIES_RESET:'GET_MOVIES_RESET',
    GET_MOVIE_BY_ID_SUCCESS:'GET_MOVIE_BY_ID_SUCCESS',
    GET_MOVIE_BY_ID_ERROR:'GET_MOVIE_BY_ID_ERROR',
    GET_COMMENTS_BY_ID_SUCCESS:'GET_COMMENTS_BY_ID_SUCCESS',
    GET_COMMENTS_BY_ID_ERROR:'GET_COMMENTS_BY_ID_ERROR',
    RESET_STATE:'RESET_STATE',

}
